# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'NWRN' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NWRN
  pod 'Alamofire', '~> 4.7'
  pod 'SlideMenuControllerSwift'
  
  # Pods from RN
  # Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly
  pod 'React', :path => '../nwrn/node_modules/react-native', :subspecs => [
      'Core',
      'CxxBridge', # Include this for RN >= 0.47
      'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
      'RCTText',
      'RCTNetwork',
      'RCTWebSocket', # needed for debugging
      # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../nwrn/node_modules/react-native/ReactCommon/yoga'
  
  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../nwrn/node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../nwrn/node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../nwrn/node_modules/react-native/third-party-podspecs/Folly.podspec'

  target 'NWRNTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NWRNUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
